# -*- coding: utf-8 -*-
"""IndianLiver.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1egpjYtjh-WbEcNgGGhjHyZ6nIiVF8GVT
"""

import seaborn as sns
import pandas as pd
import numpy as np
import sklearn
from scipy import stats
import matplotlib.pyplot as plt
import os
import seaborn as sns
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import scale

#import the dataset from specified Location
data = pd.read_csv('/content/indian_liver_patient.csv')

#showing the data from top 5
data.head()

data.info()

data.isnull().any()

data.isnull().sum()

data['Albumin_and_Globulin_Ratio'].fillna(data['Albumin_and_Globulin_Ratio'].mode()[0], inplace=True)

lc = LabelEncoder() 
data['Gender'] = lc.fit_transform(data['Gender'])

data.describe()

sns.distplot(data['Age'])
plt.title('Age Distribution Graph')
plt.show()

sns.countplot(x=data['Albumin'],hue=data['Gender'])

plt.figure(figsize=(10,7))
sns.heatmap(data.corr(), annot=True)

x_scaled=data

x_scaled.head()

x=data.iloc[:,:-1] 
y=data.Albumin